
# ------- DO NOT EDIT ------- #
PATH_ROOT: str = ""
LOG_CONF: dict = ""

VERSION = "0.6.1"
VERSION_CONFIGURATOR = "0.4.0"
VERSION_CONFIGURATOR_CUI = "0.4.0"
VERSION_CONFIGURATOR_GUI = "0.5.1"
VERSION_CONFIGURATION = "1.0.1"

VERSION_LAUNCH = "1.0.2"
VERSION_SETUP = "1.0.1"
VERSION_UPDATE = "1.0.2"
VERSION_FRONTENT_CUI = "0.2.0"
VERSION_FRONTENT_GUI = "0.3.0"

PATH_USERCONFIG = ""
FILE_USERCONFIG = "userconfig.json"

USER_CONFIGURATION: dict = {}
# --------------------------- #